schema_version: 1

context:
  name: qmpy
  version: 1.4.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/qmpy-${{ version }}.tar.gz
  sha256: 6547c16c0315ba08acd9ab9e73143a08101f76644b768b968a862d71a171ffce

build:
  number: 2
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - setuptools
    - python ${{ python_min }}.*
  run:
    - ase
    - bokeh
    - django <2.3
    - django-crispy-forms
    - django-extensions >2.2.5
    - djangorestframework >3.10.0
    - djangorestframework-filters
    - djangorestframework-queryfields
    - djangorestframework-xml
    - djangorestframework-yaml
    - jinja2 <3.0
    - lark-parser
    - lxml
    - matplotlib-base
    - mysqlclient
    - networkx
    - numpy
    - pexpect
    - pulp
    - pycifrw >=4.3
    - pygraphviz
    - pyparsing
    - pytest
    - python >=${{ python_min }}
    - python-memcached
    - pyyaml
    - requests
    - scikit-learn
    - scipy
    - spglib >1.10

tests:
  - python:
      imports:
        - qmpy
        - qmpy.analysis
      pip_check: true

      python_version: ${{ python_min }}.*
about:
  license: MIT
  license_file: LICENSE.txt
  summary: A suite of computational materials science tools.
  description: |
    A toolkit for storing crystal structure data, automating
    density-functional calculations, handling computational resources and
    performing thermodynamic analysis. qmpy is used to run and maintain
    the Open Quantum Materials Database (oqmd.org).
  homepage: http://www.oqmd.org/
  repository: https://github.com/wolverton-research-group/qmpy
  documentation: http://www.oqmd.org/static/docs/index.html

extra:
  recipe-maintainers:
    - jan-janssen
